//
// APIOrderTransactionData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APIOrderTransactionData: Codable, JSONEncodable, Hashable {

    public var orderId: Int?
    public var transactionId: String?

    public init(orderId: Int? = nil, transactionId: String? = nil) {
        self.orderId = orderId
        self.transactionId = transactionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId = "OrderId"
        case transactionId = "TransactionId"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encodeIfPresent(transactionId, forKey: .transactionId)
    }
}

