//
// APIOrderOrderComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APIOrderOrderComment: Codable, JSONEncodable, Hashable {

    public var orderId: Int?
    public var comment: String?
    public var system: Bool?

    public init(orderId: Int? = nil, comment: String? = nil, system: Bool? = nil) {
        self.orderId = orderId
        self.comment = comment
        self.system = system
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderId = "OrderId"
        case comment = "Comment"
        case system = "System"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encodeIfPresent(system, forKey: .system)
    }
}

