//
// BrandModelsWriteBrand.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A brand. */
public struct BrandModelsWriteBrand: Codable, JSONEncodable, Hashable {

    /** The name of this brand. */
    public var name: String?
    /** External Id of the brand. */
    public var externalId: String?
    /** The localized descriptions of the brand. */
    public var descriptions: [SharedModelsLocalizableContent]?

    public init(name: String? = nil, externalId: String? = nil, descriptions: [SharedModelsLocalizableContent]? = nil) {
        self.name = name
        self.externalId = externalId
        self.descriptions = descriptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case externalId = "ExternalId"
        case descriptions = "Descriptions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(descriptions, forKey: .descriptions)
    }
}

