//
// CategoryModelsCategoryQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A query to filter categories by. */
public struct CategoryModelsCategoryQuery: Codable, JSONEncodable, Hashable {

    /** Limits query to categories created after the specified date. */
    public var createdAfter: Date?
    /** Limits query to only include the supplied category ids. */
    public var categoryIds: [Int]?

    public init(createdAfter: Date? = nil, categoryIds: [Int]? = nil) {
        self.createdAfter = createdAfter
        self.categoryIds = categoryIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAfter = "CreatedAfter"
        case categoryIds = "CategoryIds"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdAfter, forKey: .createdAfter)
        try container.encodeIfPresent(categoryIds, forKey: .categoryIds)
    }
}

