//
// CategoryModelsWriteCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A category to create or update. */
public struct CategoryModelsWriteCategory: Codable, JSONEncodable, Hashable {

    /** The unique identifier of the parent category of this category. */
    public var parentCategoryId: Int?
    /** The localizable names of the category. */
    public var names: [SharedModelsLocalizableContent]?
    /** The localized descriptions of the category. */
    public var descriptions: [SharedModelsLocalizableContent]?

    public init(parentCategoryId: Int? = nil, names: [SharedModelsLocalizableContent]? = nil, descriptions: [SharedModelsLocalizableContent]? = nil) {
        self.parentCategoryId = parentCategoryId
        self.names = names
        self.descriptions = descriptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parentCategoryId = "ParentCategoryId"
        case names = "Names"
        case descriptions = "Descriptions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(parentCategoryId, forKey: .parentCategoryId)
        try container.encodeIfPresent(names, forKey: .names)
        try container.encodeIfPresent(descriptions, forKey: .descriptions)
    }
}

