//
// ContainerRestrictionSetupContainerRestrictionConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContainerRestrictionSetupContainerRestrictionConfiguration: Codable, JSONEncodable, Hashable {

    public enum AllowedLayouts: String, Codable, CaseIterable {
        case _0 = 0
        case _1 = 1
        case _2 = 2
        case _3 = 3
        case _4 = 4
        case _5 = 5
        case _6 = 6
        case _7 = 7
        case _8 = 8
    }
    public var allowedLayouts: [AllowedLayouts]?
    public var bannedWidgets: [UUID]?

    public init(allowedLayouts: [AllowedLayouts]? = nil, bannedWidgets: [UUID]? = nil) {
        self.allowedLayouts = allowedLayouts
        self.bannedWidgets = bannedWidgets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowedLayouts = "AllowedLayouts"
        case bannedWidgets = "BannedWidgets"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allowedLayouts, forKey: .allowedLayouts)
        try container.encodeIfPresent(bannedWidgets, forKey: .bannedWidgets)
    }
}

