//
// OrderValidateOrderCreationRequestStockItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderValidateOrderCreationRequestStockItem: Codable, JSONEncodable, Hashable {

    public var itemId: Int?
    public var quantity: Int?

    public init(itemId: Int? = nil, quantity: Int? = nil) {
        self.itemId = itemId
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemId = "ItemId"
        case quantity = "Quantity"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(itemId, forKey: .itemId)
        try container.encodeIfPresent(quantity, forKey: .quantity)
    }
}

