//
// OrderFreightClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderFreightClass: Codable, JSONEncodable, Hashable {

    public enum TypeAsEnum: Int, Codable, CaseIterable {
        case _0 = 0
        case _1 = 1
        case _2 = 2
    }
    public var id: Int?
    public var type: Int?
    public var name: String?
    public var typeAsEnum: TypeAsEnum?

    public init(id: Int? = nil, type: Int? = nil, name: String? = nil, typeAsEnum: TypeAsEnum? = nil) {
        self.id = id
        self.type = type
        self.name = name
        self.typeAsEnum = typeAsEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case type = "Type"
        case name = "Name"
        case typeAsEnum = "TypeAsEnum"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(typeAsEnum, forKey: .typeAsEnum)
    }
}

