//
// PaymentModelsPaymentOptionQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentModelsPaymentOptionQuery: Codable, JSONEncodable, Hashable {

    public var siteId: Int?
    /** Customer email address */
    public var email: String?
    public var customerTypeId: Int?
    public var countryId: Int?
    public var sum: Double?

    public init(siteId: Int? = nil, email: String? = nil, customerTypeId: Int? = nil, countryId: Int? = nil, sum: Double? = nil) {
        self.siteId = siteId
        self.email = email
        self.customerTypeId = customerTypeId
        self.countryId = countryId
        self.sum = sum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case siteId = "SiteId"
        case email = "Email"
        case customerTypeId = "CustomerTypeId"
        case countryId = "CountryId"
        case sum = "Sum"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(siteId, forKey: .siteId)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(customerTypeId, forKey: .customerTypeId)
        try container.encodeIfPresent(countryId, forKey: .countryId)
        try container.encodeIfPresent(sum, forKey: .sum)
    }
}

