//
// ProductModelsReadImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductModelsReadImage: Codable, JSONEncodable, Hashable {

    public var productId: Int?
    /** Url of Image */
    public var url: String?
    /** Order of image (ascending). First image is the main image for the product. */
    public var order: Int?

    public init(productId: Int? = nil, url: String? = nil, order: Int? = nil) {
        self.productId = productId
        self.url = url
        self.order = order
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "ProductId"
        case url = "Url"
        case order = "Order"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(order, forKey: .order)
    }
}

