//
// ProductModelsProductCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductModelsProductCategory: Codable, JSONEncodable, Hashable {

    /** The id of the category. */
    public var categoryId: Int?

    public init(categoryId: Int? = nil) {
        self.categoryId = categoryId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId = "CategoryId"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
    }
}

