//
// ProductModelsWriteRelatedProduct.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A related product. */
public struct ProductModelsWriteRelatedProduct: Codable, JSONEncodable, Hashable {

    /** The unique identifier for the related product. */
    public var relatedProductId: String?
    /** The product relation type id. */
    public var relationTypeId: Int?

    public init(relatedProductId: String? = nil, relationTypeId: Int? = nil) {
        self.relatedProductId = relatedProductId
        self.relationTypeId = relationTypeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relatedProductId = "RelatedProductId"
        case relationTypeId = "RelationTypeId"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(relatedProductId, forKey: .relatedProductId)
        try container.encodeIfPresent(relationTypeId, forKey: .relationTypeId)
    }
}

