//
// ProductProductItemEnvelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An envelope for the result of and action taken on a product item. */
public struct ProductProductItemEnvelope: Codable, JSONEncodable, Hashable {

    /** A status message for the action taken. */
    public var message: String?
    public var item: ProductModelsReadProductItem?

    public init(message: String? = nil, item: ProductModelsReadProductItem? = nil) {
        self.message = message
        self.item = item
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message = "Message"
        case item = "Item"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(item, forKey: .item)
    }
}

