//
// SupplierModelsSupplierQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A supplier query. */
public struct SupplierModelsSupplierQuery: Codable, JSONEncodable, Hashable {

    /** Limits query to suppliers with a name containing the specified string. */
    public var nameContains: String?
    /** Limits query to externalIds */
    public var externalIds: [String]?

    public init(nameContains: String? = nil, externalIds: [String]? = nil) {
        self.nameContains = nameContains
        self.externalIds = externalIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nameContains = "NameContains"
        case externalIds = "ExternalIds"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nameContains, forKey: .nameContains)
        try container.encodeIfPresent(externalIds, forKey: .externalIds)
    }
}

