//
// VariantModelsReadVariant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A variant of a product. */
public struct VariantModelsReadVariant: Codable, JSONEncodable, Hashable {

    /** The id of the product this variant information belongs to */
    public var productId: Int?
    /** The id of the group this variant belongs to. */
    public var groupId: Int?
    /** The name of the variant information, eg \"Weight\", \"Length\" etc */
    public var label: String?
    /** The value of the variant information, eg \"250g\", \"89cm\" etc */
    public var value: String?

    public init(productId: Int? = nil, groupId: Int? = nil, label: String? = nil, value: String? = nil) {
        self.productId = productId
        self.groupId = groupId
        self.label = label
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "ProductId"
        case groupId = "GroupId"
        case label = "Label"
        case value = "Value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encodeIfPresent(groupId, forKey: .groupId)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

