//
// VariantModelsWriteVariant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A variant of a product. */
public struct VariantModelsWriteVariant: Codable, JSONEncodable, Hashable {

    /** The name of the variant, eg \"Color\", \"Weight\" etc. */
    public var label: String?
    /** The value of this variant, eg \"Blue\", \"250g\" etc. */
    public var value: String?

    public init(label: String? = nil, value: String? = nil) {
        self.label = label
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case label = "Label"
        case value = "Value"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

